export const TOKEN_FOOTER_NEWSLETTER_SUBMIT = 'TOKEN_FOOTER_NEWSLETTER_SUBMIT';
export const TOKEN_FOOTER_NEWSLETTER_FORM = 'TOKEN_FOOTER_NEWSLETTER_FORM';
export const TOKEN_FOOTER_NEWSLETTER_ERROR = 'TOKEN_FOOTER_NEWSLETTER_ERROR';
export const TOKEN_FOOTER_NEWSLETTER_STATUS = 'TOKEN_FOOTER_NEWSLETTER_STATUS';
