export const TOKEN_FORGOT_PASSWORD_FORM_SUBMIT = 'TOKEN_FORGOT_PASSWORD_FORM_SUBMIT';
export const TOKEN_FORGOT_PASSWORD_FORM_FORM = 'TOKEN_FORGOT_PASSWORD_FORM_FORM';
export const TOKEN_FORGOT_PASSWORD_FORM_ERROR = 'TOKEN_FORGOT_PASSWORD_FORM_ERROR';
export const TOKEN_FORGOT_PASSWORD_FORM_STATUS = 'TOKEN_FORGOT_PASSWORD_FORM_STATUS';
