export const TOKEN_JOB_OFFER_INQUIRY_SUBMIT = 'TOKEN_JOB_OFFER_INQUIRY_SUBMIT';
export const TOKEN_JOB_OFFER_INQUIRY_FORM = 'TOKEN_JOB_OFFER_INQUIRY_FORM';
export const TOKEN_JOB_OFFER_INQUIRY_ERROR = 'TOKEN_JOB_OFFER_INQUIRY_ERROR';
export const TOKEN_JOB_OFFER_INQUIRY_STATUS = 'TOKEN_JOB_OFFER_INQUIRY_STATUS';
export const TOKEN_JOB_OFFER_INQUIRY_RESET = 'TOKEN_JOB_OFFER_INQUIRY_RESET';
