export const TOKEN_LOGIN_FORM_SUBMIT = 'TOKEN_LOGIN_FORM_SUBMIT';
export const TOKEN_LOGIN_FORM_FORM = 'TOKEN_LOGIN_FORM_FORM';
export const TOKEN_LOGIN_FORM_ERROR = 'TOKEN_LOGIN_FORM_ERROR';
export const TOKEN_LOGIN_FORM_STATUS = 'TOKEN_LOGIN_FORM_STATUS';
