export const TOKEN_MANAGER_FILTERS = 'TOKEN_MANAGER_FILTERS';
export const TOKEN_MANAGER_FILTERS_SELECTS = 'TOKEN_MANAGER_FILTERS_SELECTS';
export const TOKEN_MANAGER_FILTERS_CATEGORIES = 'TOKEN_MANAGER_FILTERS_CATEGORIES';
export const TOKEN_MANAGER_CLEAR_FILTERS = 'TOKEN_MANAGER_CLEAR_FILTERS'
export const TOKEN_MANAGER_CLEAR_SEARCH = 'TOKEN_MANAGER_CLEAR_SEARCH'
export const TOKEN_MANAGER_CHANGED_FILTERS = 'TOKEN_MANAGER_CHANGED_FILTERS'
export const TOKEN_MANAGER_DOWNLOAD_PRESENTATION = 'TOKEN_MANAGER_DOWNLOAD_PRESENTATION'