export const TOKEN_MODAL_RECIPES_FILTER_SUBMIT = 'TOKEN_MODAL_RECIPES_FILTER_SUBMIT';
export const TOKEN_MODAL_RECIPES_FILTER_CATEGORIES = 'TOKEN_MODAL_RECIPES_FILTER_CATEGORIES';
export const TOKEN_MODAL_RECIPES_FILTER_PRODUCTS = 'TOKEN_MODAL_RECIPES_FILTER_PRODUCTS';
export const TOKEN_MODAL_RECIPES_FILTER_COOKING_TIME = 'TOKEN_MODAL_RECIPES_FILTER_COOKING_TIME';
export const TOKEN_MODAL_RECIPES_FILTER_ERROR = 'TOKEN_MODAL_RECIPES_FILTER_ERROR';
export const TOKEN_MODAL_RECIPES_FILTER_STATUS = 'TOKEN_MODAL_RECIPES_FILTER_STATUS';
