export const TOKEN_MODAL_PRODUCT_INQUIRY_SUBMIT = 'TOKEN_MODAL_PRODUCT_INQUIRY_SUBMIT';
export const TOKEN_MODAL_PRODUCT_INQUIRY_FORM = 'TOKEN_MODAL_PRODUCT_INQUIRY_FORM';
export const TOKEN_MODAL_PRODUCT_INQUIRY_ERROR = 'TOKEN_MODAL_PRODUCT_INQUIRY_ERROR';
export const TOKEN_MODAL_PRODUCT_INQUIRY_STATUS = 'TOKEN_MODAL_PRODUCT_INQUIRY_STATUS';
