export const TOKEN_MODAL_NEWSLETTER_SUBMIT = 'TOKEN_MODAL_NEWSLETTER_SUBMIT';
export const TOKEN_MODAL_NEWSLETTER_FORM = 'TOKEN_MODAL_NEWSLETTER_FORM';
export const TOKEN_MODAL_NEWSLETTER_ERROR = 'TOKEN_MODAL_NEWSLETTER_ERROR';
export const TOKEN_MODAL_NEWSLETTER_STATUS = 'TOKEN_MODAL_NEWSLETTER_STATUS';
