export const TOKEN_RESET_PASSWORD_FORM_SUBMIT = 'TOKEN_RESET_PASSWORD_FORM_SUBMIT';
export const TOKEN_RESET_PASSWORD_FORM_FORM = 'TOKEN_RESET_PASSWORD_FORM_FORM';
export const TOKEN_RESET_PASSWORD_FORM_ERROR = 'TOKEN_RESET_PASSWORD_FORM_ERROR';
export const TOKEN_RESET_PASSWORD_FORM_STATUS = 'TOKEN_RESET_PASSWORD_FORM_STATUS';
